### ISSUE TITLE
Recommended branch

### ISSUE THREAD

**Issue by sivadasetty** [PabloPiaggi/LAMMPS_ChiralTetramer#2]
Hi @PabloPiaggi: I am exploring your code for studying chiral systems. Which branch should I use (chiral/chiral-smooth) for simulating the systems in your paper https://doi.org/10.1063/5.0161732. Also, do you have any installation script with recommended versions for compiler? Thanks!

**Comment by PabloPiaggi** [comment]
Hi @sivadasetty , I believe the chiral branch is the correct one. I don't have a recommended version for compilers.
